name: Build and Deploy JupyterLite

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite
        run: |
          python -m pip install --upgrade pip
          pip install jupyterlite-core==0.3.0
          pip install jupyterlite-pyodide-kernel==0.3.2
          pip install jupyterlite-pyodide-lock==0.8.0

      - name: Build JupyterLite site
        run: |
          jupyter-lite build --contents content --output-dir dist --piplite-wheels https://pypi.org/pypi/{package_name}/json
          
      - name: List built files
        run: |
          echo "Files in dist:"
          ls -la dist/
          echo "Files in dist/files:"
          ls -la dist/files/ || echo "No files directory"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
